### ISSUE TITLE
No animation in example

### ISSUE THREAD

**Issue by jntagadiad** [landxcape/animated_marker#3]
Did I missed something important? I run the example app but there's only 3 static markers.

**Comment by landxcape** [comment]
Hi, thanks for your interest, can you show me how you did it?
just wrap the GoogleMap with AnimatedMarker,
pass your markers to "animatedMarkers" that you wish to animate, and to "staticMarkers" that you don't want to animate,
then pass the "animatedMarkers" from the "builder" to your GoogleMap,
then, when the markers changes positions, it will animate to the new position,
(note: the markers passed to "animatedMarkers" will animate and "staticMarkers" will not)

**Comment by landxcape** [comment]
Also, please try the "Example" code, I haven't updated the code from "Readme"

**Comment by landxcape** [comment]
Thank you @0wzZZzz6 for getting this to my attention,
example code did have some bugs, I have fixed them and pushed them to the main branch
you can also add it to your pubspec.yaml and try directly from there

**Comment by jntagadiad** [comment]
@landxcape I can see the animation now, I have another question regarding continuous animation between markers. Currently there's a delay from one marker to other marker.

**Comment by jntagadiad** [comment]
@landxcape Nevermind, I just testing the repo and adjusted the stream. Thanks a lot for this awesome package!
